FORMAT: 1A
HOST: http://localhost:5000/api

#ItemCatalog

## Category collection [/categories]

### List all categories [GET]

+ Response 200 (application/json)

        {
          "data": [
            {
              "id": 1, 
              "name": "Soccer", 
              "slug": "soccer"
            }, 
            {
              "id": 2, 
              "name": "Basketball", 
              "slug": "basketball"
            }
          ], 
          "success": true
        }
        
### Category details [GET /cartegories/{slug}]

+ Parameters
    + slug (string) - slug of a category

+ Response 400 (application/json)

        {
            "message": "Category not found!", 
            "success": false
        }
        
+ Response 200 (application/json)
        
        {
            "data": {
                "id": 1, 
                "items": [], 
                "name": "Soccer", 
                "slug": "soccer"
            }, 
            "success": true
        }
        
## Item collection [/items]

### Get latest items [GET /items/latest]

+ Response 200 (application/json)
    
        {
            "data": [
                {
                  "category": {
                    "id": 2, 
                    "name": "Basketball", 
                    "slug": "basketball"
                  }, 
                  "id": 2, 
                  "name": "item 2", 
                  "slug": "item-2"
                }, 
                {
                  "category": {
                    "id": 1, 
                    "name": "Soccer", 
                    "slug": "soccer"
                  }, 
                  "id": 1, 
                  "name": "item 1", 
                  "slug": "item-1"
                }
            ], 
            "success": true
        }

### Get item details [GET /items/{id}]

+ Parameters
    + id (number) - Id of a item
        
+ Response 200 (application/json)

        {
            "data": {
                "category": {
                  "id": 1, 
                  "name": "Soccer", 
                  "slug": "soccer"
                }, 
                "description": "item 1 desc", 
                "id": 1, 
                "name": "item 1", 
                "slug": "item-1", 
                "userId": 1
            }, 
            "success": true
        }

+ Response 400 (application/json)

        {
            "message": "Item not found!", 
            "success": false
        }
        
### Add an item [POST /items]